unpackaged/main/default/objects/Asset/fields/Asset_Search_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Search_Type__c</fullName>
    <label>Asset Search Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>Burner</fullName>
            </value>
            <value>
                <fullName>CGP</fullName>
            </value>
            <value>
                <fullName>Containment</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>Engine/Compressor</fullName>
            </value>
            <value>
                <fullName>Exchanger</fullName>
            </value>
            <value>
                <fullName>Flowline</fullName>
            </value>
            <value>
                <fullName>Gas Plant</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Instrumentation</fullName>
            </value>
            <value>
                <fullName>Meter</fullName>
            </value>
            <value>
                <fullName>Pad</fullName>
            </value>
            <value>
                <fullName>Pawnee Plant</fullName>
            </value>
            <value>
                <fullName>Pigging</fullName>
            </value>
            <value>
                <fullName>Piping</fullName>
            </value>
            <value>
                <fullName>Pneu Blowcase</fullName>
            </value>
            <value>
                <fullName>Pneumatics</fullName>
            </value>
            <value>
                <fullName>POD</fullName>
            </value>
            <value>
                <fullName>PUMP</fullName>
            </value>
            <value>
                <fullName>Pumping Unit</fullName>
            </value>
            <value>
                <fullName>Rectifier</fullName>
            </value>
            <value>
                <fullName>Relief Valve</fullName>
            </value>
            <value>
                <fullName>Satellite</fullName>
            </value>
            <value>
                <fullName>Separator</fullName>
            </value>
            <value>
                <fullName>Separator H2S Scavenger</fullName>
            </value>
            <value>
                <fullName>Skid FG Conditioner</fullName>
            </value>
            <value>
                <fullName>Skid Instrument Air Unit</fullName>
            </value>
            <value>
                <fullName>STAT Office</fullName>
            </value>
            <value>
                <fullName>Sump</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Type_Picklist</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Equip_ID__c.field-meta.xml
<CustomField>
    <fullName>Equip_ID__c</fullName>
    <label>Equip ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/Downtime_Log__c.object-meta.xml
<CustomObject>
    <label>Downtime Log</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>Downtime Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Downtime Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Downtime_Log__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Asset_Type__c</field>
            <operation>equals</operation>
            <value>Engine/Compressor, Well</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Downtime Logs</relationshipLabel>
    <relationshipName>Downtime_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Downtime_Code__c.field-meta.xml
<CustomField>
    <fullName>Downtime_Code__c</fullName>
    <label>Downtime Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Parent_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>54</fullName>
                <label>Cat. Conv. Temp. High</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Chemical Treatment</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>Compressor Issue</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Compressor Issues</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Compressor PM</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>Cooling Water Level Low</label>
            </value>
            <value>
                <fullName>47</fullName>
                <label>Cooling Water Temperature High</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>Down-hole Issue/ No Flow</label>
            </value>
            <value>
                <fullName>44</fullName>
                <label>Facility Maintenance</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Facility  Maintenance</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Flowline Maintenance</label>
            </value>
            <value>
                <fullName>58</fullName>
                <label>Force Majeure</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Freezing Issue/ Hydrates</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Fueld Gas Supply</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Gas Lift</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Gas  Lift</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Gas Plant Shut-in</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>Gas Temperature High</label>
            </value>
            <value>
                <fullName>57</fullName>
                <label>High Discharge Pressure</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>High Pipeline Pressure</label>
            </value>
            <value>
                <fullName>59</fullName>
                <label>High Sales Line Pressure</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Hot Water Operations</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Hot-Water Operations</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>I&amp;E Issue</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Loaded Up/ Incapable of flow</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>Lube No Flow</label>
            </value>
            <value>
                <fullName>49</fullName>
                <label>Lube Oil Level High</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>Lube Oil Pressure High</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>Lube Oil Temperature High</label>
            </value>
            <value>
                <fullName>Not In Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Downtime_Type__c.field-meta.xml
<CustomField>
    <fullName>Downtime_Type__c</fullName>
    <label>Downtime Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compressor Downtime</fullName>
            </value>
            <value>
                <fullName>Well Downtime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Duration_hrs__c.field-meta.xml
<CustomField>
    <fullName>Duration_hrs__c</fullName>
    <label>Duration (hrs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_equip_id__c.field-meta.xml
<CustomField>
    <fullName>integration_equip_id__c</fullName>
    <inlineHelpText>Value from integration file</inlineHelpText>
    <label>integration_equip_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_equip_name__c.field-meta.xml
<CustomField>
    <fullName>integration_equip_name__c</fullName>
    <inlineHelpText>Value fro integration file</inlineHelpText>
    <label>integration_equip_name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_events__c.field-meta.xml
<CustomField>
    <fullName>integration_events__c</fullName>
    <label>integration_events</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_id__c.field-meta.xml
<CustomField>
    <fullName>integration_id__c</fullName>
    <label>integration id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_longest_ts__c.field-meta.xml
<CustomField>
    <fullName>integration_longest_ts__c</fullName>
    <label>integration longest_ts</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_meterId__c.field-meta.xml
<CustomField>
    <fullName>integration_meterId__c</fullName>
    <label>integration meterId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/intergration_flowType__c.field-meta.xml
<CustomField>
    <fullName>intergration_flowType__c</fullName>
    <label>intergration flowType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/longest_occur__c.field-meta.xml
<CustomField>
    <fullName>longest_occur__c</fullName>
    <label>longest_occur</label>
    <precision>17</precision>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Parent_Code__c.field-meta.xml
<CustomField>
    <fullName>Parent_Code__c</fullName>
    <label>Parent Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Downtime_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>42</fullName>
                <label>Planned</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Planned/Subsurface</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planned/Surface</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Un-Planned</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Un-Planned/Subsurface</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Un-Planned/Surface</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Send_To_ProCount__c.field-meta.xml
<CustomField>
    <fullName>Send_To_ProCount__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to send to ProCount</inlineHelpText>
    <label>Send To ProCount</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/globalValueSets/Asset_Type_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Actuator</fullName>
    </customValue>
    <customValue>
        <fullName>Area</fullName>
    </customValue>
    <customValue>
        <fullName>Blowdown Vessel</fullName>
    </customValue>
    <customValue>
        <fullName>Burner Combustor</fullName>
    </customValue>
    <customValue>
        <fullName>Burner Flare</fullName>
    </customValue>
    <customValue>
        <fullName>Burner Incinerator</fullName>
    </customValue>
    <customValue>
        <fullName>Central Facility</fullName>
    </customValue>
    <customValue>
        <fullName>CGP</fullName>
    </customValue>
    <customValue>
        <fullName>Cntrl Pneu</fullName>
    </customValue>
    <customValue>
        <fullName>Cntrol Pneu</fullName>
    </customValue>
    <customValue>
        <fullName>Comp Air</fullName>
    </customValue>
    <customValue>
        <fullName>Comp Reciprocating</fullName>
    </customValue>
    <customValue>
        <fullName>Compressor</fullName>
    </customValue>
    <customValue>
        <fullName>Compressor Station</fullName>
    </customValue>
    <customValue>
        <fullName>Comp Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Contactor</fullName>
    </customValue>
    <customValue>
        <fullName>Containment</fullName>
    </customValue>
    <customValue>
        <fullName>Containment Concrete</fullName>
    </customValue>
    <customValue>
        <fullName>Containment Earthen</fullName>
    </customValue>
    <customValue>
        <fullName>Containment Steel Lined</fullName>
    </customValue>
    <customValue>
        <fullName>Containment Steel Unlined</fullName>
    </customValue>
    <customValue>
        <fullName>Department</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Location</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Overhead</fullName>
    </customValue>
    <customValue>
        <fullName>Eng EG AJAX DCP180</fullName>
    </customValue>
    <customValue>
        <fullName>Eng EG AJAX DCP230</fullName>
    </customValue>
    <customValue>
        <fullName>Eng EG AJAX DCP360</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Engine/Compressor</fullName>
    </customValue>
    <masterLabel>Asset Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/dowtimeLogsManagerControllerTest.cls
/**
 * @author Bruce Behrens Opportune LLP
 * @description test class for dowtimeLogsManagerController
 * @date 2-4-2020
*/
@isTest
private class dowtimeLogsManagerControllerTest {


	private static Map<String, String> Downtime_CodeMap
	{
		get {
			if (Downtime_CodeMap == null) {
				Downtime_CodeMap = new Map<String, String> ();
				Schema.DescribeFieldResult fieldResult = Downtime_Log__c.Downtime_Code__c.getDescribe();
				List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
				for (Schema.PicklistEntry pickListVal : ple) {
					Downtime_CodeMap.put(pickListVal.getLabel(), pickListVal.getValue());
				}
			}
			return Downtime_CodeMap;
		}
		set;
	}

	private static Map<String, String> Parent_CodeMap
	{
		get {
			if (Parent_CodeMap == null) {
				Parent_CodeMap = new Map<String, String> ();
				Schema.DescribeFieldResult fieldResult = Downtime_Log__c.Parent_Code__c.getDescribe();
				List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
				for (Schema.PicklistEntry pickListVal : ple) {
					Parent_CodeMap.put(pickListVal.getLabel(), pickListVal.getValue());
				}

			}
			return Parent_CodeMap;
		}
		set;
	}

	private static Map<String, String> Downtime_TypeMap
	{
		get {
			if (Downtime_TypeMap == null) {
				Downtime_TypeMap = new Map<String, String> ();
				Schema.DescribeFieldResult fieldResult = Downtime_Log__c.Downtime_Type__c.getDescribe();
				List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
				for (Schema.PicklistEntry pickListVal : ple) {
					Downtime_TypeMap.put(pickListVal.getLabel(), pickListVal.getValue());
				}

			}
			return Downtime_TypeMap;
		}
		set;
	}

	@isTest
	private static void getDowntimeLogsTest() {
		Account acc1 = new Account();
		acc1.Name = 'Test Account';
		insert acc1;

		Asset a1 = new Asset();
		a1.Name = 'test asset';
		a1.Asset_Type__c = 'CGP';
		a1.Asset_Search_Type__c = 'CGP';
		a1.Equip_ID__c = '99999';
		a1.AccountId = acc1.Id;
		insert a1;

		Downtime_Log__c dtlog = new Downtime_Log__c();
		dtlog.integration_id__c = '1234';
		dtlog.Date__c = Date.today();
		dtlog.integration_equip_name__c = '1234';
		dtlog.integration_equip_id__c = '1234';
		dtlog.integration_meterId__c = '1234';
		dtlog.intergration_flowType__c = '1234';
		dtlog.integration_events__c = '1234';
		dtlog.longest_occur__c = 24;
		dtlog.integration_longest_ts__c = Date.today();
		dtlog.Duration_hrs__c = 24;
		dtlog.Downtime_Type__c = Downtime_TypeMap.get('Compressor Downtime');
		dtlog.Parent_Code__c = Parent_CodeMap.get('Un-Planned');
		dtlog.Downtime_Code__c = Downtime_CodeMap.get('Cat. Conv. Temp. High');
		dtlog.Asset__c = a1.Id;
		dtlog.Send_To_ProCount__c = true;
		insert dtlog;

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		map<string, string> searchfor = new map<string, string> ();
		searchfor.put('Asset__c', 'test asset');
		list<Sobject> test1 = dowtimeLogsManagerController.getDowntimeLogs(searchfor);
		Test.stopTest();

		System.assertEquals(1, test1.size());

	}

	@isTest
	private static void copyLogsTest() {
		Account acc1 = new Account();
		acc1.Name = 'Test Account';
		insert acc1;

		Asset a1 = new Asset();
		a1.Name = 'test asset';
		a1.Asset_Type__c = 'CGP';
		a1.Asset_Search_Type__c = 'CGP';
		a1.Equip_ID__c = '99999';
		a1.AccountId = acc1.Id;
		insert a1;

		Downtime_Log__c dtlog = new Downtime_Log__c();
		dtlog.integration_id__c = '1234';
		dtlog.Date__c = Date.today();
		dtlog.integration_equip_name__c = '1234';
		dtlog.integration_equip_id__c = '1234';
		dtlog.integration_meterId__c = '1234';
		dtlog.intergration_flowType__c = '1234';
		dtlog.integration_events__c = '1234';
		dtlog.longest_occur__c = 24;
		dtlog.integration_longest_ts__c = Date.today();
		dtlog.Duration_hrs__c = 24;
		dtlog.Downtime_Type__c = Downtime_TypeMap.get('Compressor Downtime');
		dtlog.Parent_Code__c = Parent_CodeMap.get('Un-Planned');
		dtlog.Downtime_Code__c = Downtime_CodeMap.get('Cat. Conv. Temp. High');
		dtlog.Asset__c = a1.Id;
		dtlog.Send_To_ProCount__c = true;
		insert dtlog;

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		String test1 = dowtimeLogsManagerController.copyLogs(new List<Id>{dtlog.Id}, Date.today().addDays(1));
		Test.stopTest();

		System.assertEquals('', test1);

	}

	@isTest
	private static void deleteLogsTest() {
		Account acc1 = new Account();
		acc1.Name = 'Test Account';
		insert acc1;

		Asset a1 = new Asset();
		a1.Name = 'test asset';
		a1.Asset_Type__c = 'CGP';
		a1.Asset_Search_Type__c = 'CGP';
		a1.Equip_ID__c = '99999';
		a1.AccountId = acc1.Id;
		insert a1;

		Downtime_Log__c dtlog = new Downtime_Log__c();
		dtlog.integration_id__c = '1234';
		dtlog.Date__c = Date.today();
		dtlog.integration_equip_name__c = '1234';
		dtlog.integration_equip_id__c = '1234';
		dtlog.integration_meterId__c = '1234';
		dtlog.intergration_flowType__c = '1234';
		dtlog.integration_events__c = '1234';
		dtlog.longest_occur__c = 24;
		dtlog.integration_longest_ts__c = Date.today();
		dtlog.Duration_hrs__c = 24;
		dtlog.Downtime_Type__c = Downtime_TypeMap.get('Compressor Downtime');
		dtlog.Parent_Code__c = Parent_CodeMap.get('Un-Planned');
		dtlog.Downtime_Code__c = Downtime_CodeMap.get('Cat. Conv. Temp. High');
		dtlog.Asset__c = a1.Id;
		dtlog.Send_To_ProCount__c = true;
		insert dtlog;

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		String test1 = dowtimeLogsManagerController.deleteLogs(new List<Id>{dtlog.Id});
		Test.stopTest();

		System.assertEquals('', test1);

	}

}