unpackaged/main/default/objects/Asset/fields/Asset_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Type__c</fullName>
    <label>Asset Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Type_Picklist</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/Downtime_Log__c.object-meta.xml
<CustomObject>
    <label>Downtime Log</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>Downtime Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Downtime Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Downtime_Log__c/fields/Downtime_Code__c.field-meta.xml
<CustomField>
    <fullName>Downtime_Code__c</fullName>
    <label>Downtime Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Parent_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>54</fullName>
                <label>Cat. Conv. Temp. High</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Chemical Treatment</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>Compressor Issue</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Compressor Issues</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Compressor PM</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>Cooling Water Level Low</label>
            </value>
            <value>
                <fullName>47</fullName>
                <label>Cooling Water Temperature High</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>Down-hole Issue/ No Flow</label>
            </value>
            <value>
                <fullName>44</fullName>
                <label>Facility Maintenance</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Facility  Maintenance</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Flowline Maintenance</label>
            </value>
            <value>
                <fullName>58</fullName>
                <label>Force Majeure</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Freezing Issue/ Hydrates</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Fueld Gas Supply</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Gas Lift</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Gas  Lift</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Gas Plant Shut-in</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>Gas Temperature High</label>
            </value>
            <value>
                <fullName>57</fullName>
                <label>High Discharge Pressure</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>High Pipeline Pressure</label>
            </value>
            <value>
                <fullName>59</fullName>
                <label>High Sales Line Pressure</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Hot Water Operations</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Hot-Water Operations</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>I&amp;E Issue</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Loaded Up/ Incapable of flow</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>Lube No Flow</label>
            </value>
            <value>
                <fullName>49</fullName>
                <label>Lube Oil Level High</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>Lube Oil Pressure High</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>Lube Oil Temperature High</label>
            </value>
            <value>
                <fullName>Not In Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Downtime_Type__c.field-meta.xml
<CustomField>
    <fullName>Downtime_Type__c</fullName>
    <label>Downtime Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compressor Downtime</fullName>
            </value>
            <value>
                <fullName>Well Downtime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Parent_Code__c.field-meta.xml
<CustomField>
    <fullName>Parent_Code__c</fullName>
    <label>Parent Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Downtime_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>42</fullName>
                <label>Planned</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Planned/Subsurface</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planned/Surface</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Un-Planned</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Un-Planned/Subsurface</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Un-Planned/Surface</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/Ignition_ProCount_Integration_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Ignition / ProCount Integration Settings</label>
    <pluralLabel>Ignition / ProCount Integration Settings</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/Delete_Downtime_Logs_after_x_days__c.field-meta.xml
<CustomField>
    <fullName>Delete_Downtime_Logs_after_x_days__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Delete Downtime Logs after x days. Optional enter the number of days to keep downtime logs. Records will be deleted after this number of days based on last modified date. 0 or less disables the job</inlineHelpText>
    <label>Delete_Downtime_Logs_after_x_days</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/Delete_Integration_Logs_after_x_days__c.field-meta.xml
<CustomField>
    <fullName>Delete_Integration_Logs_after_x_days__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Optional enter the number of days to keep integration logs. Records will be deleted after this number of days based on last modified date. 0 or less disables the job</inlineHelpText>
    <label>Delete_Integration_Logs_after_x_days</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to enable the Integration jobs to run.</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/Ignition_ProCount_Send_Errors_to_Email__c.field-meta.xml
<CustomField>
    <fullName>Ignition_ProCount_Send_Errors_to_Email__c</fullName>
    <inlineHelpText>Enter an email to send errors that occur</inlineHelpText>
    <label>Ignition_ProCount_Send_Errors_to_Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/ProCount_File_Name__c.field-meta.xml
<CustomField>
    <fullName>ProCount_File_Name__c</fullName>
    <inlineHelpText>Enter the name of the file ProCount example: ProCount.csv</inlineHelpText>
    <label>ProCount_File_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/REST_FTP_api_Key__c.field-meta.xml
<CustomField>
    <fullName>REST_FTP_api_Key__c</fullName>
    <inlineHelpText>Enter the value to communicate with the Heroku app</inlineHelpText>
    <label>REST_FTP_api_Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/REST_FTP_Ignition_Download_Path__c.field-meta.xml
<CustomField>
    <fullName>REST_FTP_Ignition_Download_Path__c</fullName>
    <inlineHelpText>Enter the ftp path to pickup Ignition files</inlineHelpText>
    <label>REST_FTP_Ignition_Download_Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/REST_FTP_ProCount_Upload_Path__c.field-meta.xml
<CustomField>
    <fullName>REST_FTP_ProCount_Upload_Path__c</fullName>
    <inlineHelpText>Enter the ftp location to put ProCount files</inlineHelpText>
    <label>REST_FTP_ProCount_Upload_Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/REST_FTP_server__c.field-meta.xml
<CustomField>
    <fullName>REST_FTP_server__c</fullName>
    <inlineHelpText>Enter the ftp server address</inlineHelpText>
    <label>REST_FTP_server</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/REST_FTP_server_password__c.field-meta.xml
<CustomField>
    <fullName>REST_FTP_server_password__c</fullName>
    <inlineHelpText>Enter ftp password</inlineHelpText>
    <label>REST_FTP_server_password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/REST_FTP_server_port__c.field-meta.xml
<CustomField>
    <fullName>REST_FTP_server_port__c</fullName>
    <inlineHelpText>Enter the ftp server port</inlineHelpText>
    <label>REST_FTP_server_port</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/REST_FTP_server_username__c.field-meta.xml
<CustomField>
    <fullName>REST_FTP_server_username__c</fullName>
    <inlineHelpText>enter the ftp username</inlineHelpText>
    <label>REST_FTP_server_username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/REST_FTP_server_useTLS__c.field-meta.xml
<CustomField>
    <fullName>REST_FTP_server_useTLS__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>check to use tls communication on the ftp</inlineHelpText>
    <label>REST_FTP_server_useTLS</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Ignition_ProCount_Integration_Settings__mdt/fields/REST_FTP_URL__c.field-meta.xml
<CustomField>
    <fullName>REST_FTP_URL__c</fullName>
    <inlineHelpText>Enter the URL from the Heroku app used to talk to a ftp server</inlineHelpText>
    <label>REST_FTP_URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Used to track and process integration data</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0}</displayFormat>
        <label>Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integration_Log__c/fields/FTP_File_Name__c.field-meta.xml
<CustomField>
    <fullName>FTP_File_Name__c</fullName>
    <label>FTP File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/FTP_File_Path__c.field-meta.xml
<CustomField>
    <fullName>FTP_File_Path__c</fullName>
    <label>FTP File Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Download Complete</fullName>
            </value>
            <value>
                <fullName>Process Completed</fullName>
            </value>
            <value>
                <fullName>Upload Complete</fullName>
            </value>
            <value>
                <fullName>Ready to Process</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Holding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ignition Downtime Export</fullName>
            </value>
            <value>
                <fullName>ProCount Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Asset_Type_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Actuator</fullName>
    </customValue>
    <customValue>
        <fullName>Area</fullName>
    </customValue>
    <customValue>
        <fullName>Blowdown Vessel</fullName>
    </customValue>
    <customValue>
        <fullName>Burner Combustor</fullName>
    </customValue>
    <customValue>
        <fullName>Burner Flare</fullName>
    </customValue>
    <customValue>
        <fullName>Burner Incinerator</fullName>
    </customValue>
    <customValue>
        <fullName>Central Facility</fullName>
    </customValue>
    <customValue>
        <fullName>CGP</fullName>
    </customValue>
    <customValue>
        <fullName>Cntrl Pneu</fullName>
    </customValue>
    <customValue>
        <fullName>Cntrol Pneu</fullName>
    </customValue>
    <customValue>
        <fullName>Comp Air</fullName>
    </customValue>
    <customValue>
        <fullName>Comp Reciprocating</fullName>
    </customValue>
    <customValue>
        <fullName>Compressor</fullName>
    </customValue>
    <customValue>
        <fullName>Compressor Station</fullName>
    </customValue>
    <customValue>
        <fullName>Comp Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Contactor</fullName>
    </customValue>
    <customValue>
        <fullName>Containment</fullName>
    </customValue>
    <customValue>
        <fullName>Containment Concrete</fullName>
    </customValue>
    <customValue>
        <fullName>Containment Earthen</fullName>
    </customValue>
    <customValue>
        <fullName>Containment Steel Lined</fullName>
    </customValue>
    <customValue>
        <fullName>Containment Steel Unlined</fullName>
    </customValue>
    <customValue>
        <fullName>Department</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Location</fullName>
    </customValue>
    <customValue>
        <fullName>Electrical Overhead</fullName>
    </customValue>
    <customValue>
        <fullName>Eng EG AJAX DCP180</fullName>
    </customValue>
    <customValue>
        <fullName>Eng EG AJAX DCP230</fullName>
    </customValue>
    <customValue>
        <fullName>Eng EG AJAX DCP360</fullName>
    </customValue>
    <customValue>
        <fullName>Engine</fullName>
    </customValue>
    <customValue>
        <fullName>Engine/Compressor</fullName>
    </customValue>
    <masterLabel>Asset Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/OP_IntegrationBatchTest.cls
/**
 * @author Bruce Behrens Opportune LLP
 * @description unit test for OP_IntegrationBatch
 * @date 1-24-2020
*/
@isTest
private class OP_IntegrationBatchTest {

	private static Ignition_ProCount_Integration_Settings__mdt getTestSettings()
	{
		Map<String, Object> fields = new Map<String, Object>
		{
			'Enabled__c' => true,
			'Ignition_ProCount_Send_Errors_to_Email__c' => 'admin@ensignnr.com',
			'ProCount_File_Name__c' => 'ProCount.csv',
			'REST_FTP_api_Key__c' => 'test',
			'REST_FTP_Ignition_Download_Path__c' => '/toSF',
			'REST_FTP_ProCount_Upload_Path__c' => 'fromSF',
			'REST_FTP_server__c' => 'test.ensignnr.com',
			'REST_FTP_server_password__c' => 'mysecert',
			'REST_FTP_server_port__c' => 21,
			'REST_FTP_server_username__c' => 'admin@ensignnr.com',
			'REST_FTP_server_useTLS__c' => false,
			'REST_FTP_URL__c' => 'https://sftoftpproxy.herokuapp.com',
			'Delete_Downtime_Logs_after_x_days__c' => 365,
			'Delete_Integration_Logs_after_x_days__c' => 365
		};
		Ignition_ProCount_Integration_Settings__mdt settings = (Ignition_ProCount_Integration_Settings__mdt) OP_Utility.getMetadata('Ignition_ProCount_Integration_Settings__mdt', fields);
		OP_Utility.OPIntegrationSettings = settings;
		return settings;

	}


	private static Map<String, String> Downtime_CodeMap
	{
		get {
			if (Downtime_CodeMap == null) {
				Downtime_CodeMap = new Map<String, String> ();
				Schema.DescribeFieldResult fieldResult = Downtime_Log__c.Downtime_Code__c.getDescribe();
				List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
				for (Schema.PicklistEntry pickListVal : ple) {
					Downtime_CodeMap.put(pickListVal.getLabel(), pickListVal.getValue());
				}
			}
			return Downtime_CodeMap;
		}
		set;
	}

	private static Map<String, String> Parent_CodeMap
	{
		get {
			if (Parent_CodeMap == null) {
				Parent_CodeMap = new Map<String, String> ();
				Schema.DescribeFieldResult fieldResult = Downtime_Log__c.Parent_Code__c.getDescribe();
				List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
				for (Schema.PicklistEntry pickListVal : ple) {
					Parent_CodeMap.put(pickListVal.getLabel(), pickListVal.getValue());
				}

			}
			return Parent_CodeMap;
		}
		set;
	}

	private static Map<String, String> Downtime_TypeMap
	{
		get {
			if (Downtime_TypeMap == null) {
				Downtime_TypeMap = new Map<String, String> ();
				Schema.DescribeFieldResult fieldResult = Downtime_Log__c.Downtime_Type__c.getDescribe();
				List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
				for (Schema.PicklistEntry pickListVal : ple) {
					Downtime_TypeMap.put(pickListVal.getLabel(), pickListVal.getValue());
				}

			}
			return Downtime_TypeMap;
		}
		set;
	}



	@isTest
	private static void IgnitionDowntimeExportDownloadTest() {

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();
		OP_IntegrationBatch.testresponse = new Map<String, HttpResponse> ();

		OP_IntegrationBatch.ResponseResult t1 = new OP_IntegrationBatch.ResponseResult();
		t1.success = true;
		t1.files = new List<String> ();
		t1.files.add('Ignition_Downtime_Export_Example.csv');
		t1.files.add('1.csv');
		HttpResponse listfiles = new HttpResponse();
		listfiles.setBody(JSON.serialize(t1));


		OP_IntegrationBatch.testresponse.put('listfiles', listfiles);



		OP_IntegrationBatch.ResponseResult t2 = new OP_IntegrationBatch.ResponseResult();
		t2.success = true;
		t2.data = 'aWQscmVwb3J0RGF0ZSxlcXVpcF9uYW1lLGVxdWlwX2lkLG1ldGVySWQsZmxvd1R5cGUsZXZlbnRzLGxvbmdlc3Rfb2NjdXIsbG9uZ2VzdF90cyxkdXJhdGlvbg0KMjI2MCwxLzI2LzIwMjAsQUZGTEVSQkFDSCAwMSAwMkggUEwsMjU0OTAsNzItMTEwNSxJbnRlcm1pdHRlciwxLDE5LjgyNDcxNSwxLzI2LzIwMjAsMTkuODI0NzE1DQoyMjYxLDEvMjYvMjAyMCxPRVRLRU4gMDEgMDFIIFBMLDI1MzgwLDcxLTMwMDIsSW50ZXJtaXR0ZXIsMSwxNy4xOTg2MiwxLzI2LzIwMjAsMTcuMTk4NjINCg==';
		HttpResponse getfile = new HttpResponse();
		getfile.setBody(JSON.serialize(t2));
		OP_IntegrationBatch.testresponse.put('getfile', getfile);

		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Ignition Downtime Export Download';
		//mybatch.continueToNextJob = false;
		database.executebatch(mybatch, 1);

		Test.stopTest();


		Integration_Log__c test1 = [Select Id from Integration_Log__c where Type__c = 'Ignition Downtime Export' and FTP_File_Name__c = 'Ignition_Downtime_Export_Example.csv'];
		System.assert(test1 != null);

		Attachment test2 = [Select Id from Attachment where ParentId = :test1.Id and Name = 'Ignition_Downtime_Export_Example.csv'];
		System.assert(test1 != null);

	}

	@isTest
	private static void IgnitionDowntimeExportDownloadStep2Test() {

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();
		OP_IntegrationBatch.testresponse = new Map<String, HttpResponse> ();

		OP_IntegrationBatch.ResponseResult t2 = new OP_IntegrationBatch.ResponseResult();
		t2.success = true;
		t2.data = 'aWQscmVwb3J0RGF0ZSxlcXVpcF9uYW1lLGVxdWlwX2lkLG1ldGVySWQsZmxvd1R5cGUsZXZlbnRzLGxvbmdlc3Rfb2NjdXIsbG9uZ2VzdF90cyxkdXJhdGlvbg0KMjI2MCwxLzI2LzIwMjAsQUZGTEVSQkFDSCAwMSAwMkggUEwsMjU0OTAsNzItMTEwNSxJbnRlcm1pdHRlciwxLDE5LjgyNDcxNSwxLzI2LzIwMjAsMTkuODI0NzE1DQoyMjYxLDEvMjYvMjAyMCxPRVRLRU4gMDEgMDFIIFBMLDI1MzgwLDcxLTMwMDIsSW50ZXJtaXR0ZXIsMSwxNy4xOTg2MiwxLzI2LzIwMjAsMTcuMTk4NjINCg==';
		HttpResponse getfile = new HttpResponse();
		getfile.setBody(JSON.serialize(t2));
		OP_IntegrationBatch.testresponse.put('getfile', getfile);

		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Ignition Downtime Export Download';
		//mybatch.continueToNextJob = false;
		mybatch.filestoprocess = new List<String> { '1.csv' };
		database.executebatch(mybatch, 1);


		Test.stopTest();


		Integration_Log__c test1 = [Select Id from Integration_Log__c where Type__c = 'Ignition Downtime Export' and FTP_File_Name__c = '1.csv'];
		System.assert(test1 != null);

		Attachment test2 = [Select Id from Attachment where ParentId = :test1.Id and Name = '1.csv'];
		System.assert(test1 != null);

	}

	@isTest
	private static void IgnitionDowntimeExportDownloadStepFTPGetFileErrorTest() {

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();
		OP_IntegrationBatch.testresponse = new Map<String, HttpResponse> ();

		OP_IntegrationBatch.ResponseResult t1 = new OP_IntegrationBatch.ResponseResult();
		t1.success = true;
		t1.files = new List<String> ();
		t1.files.add('Ignition_Downtime_Export_Example.csv');
		t1.files.add('1.csv');
		HttpResponse listfiles = new HttpResponse();
		listfiles.setBody(JSON.serialize(t1));


		OP_IntegrationBatch.testresponse.put('listfiles', listfiles);



		OP_IntegrationBatch.ResponseResult t2 = new OP_IntegrationBatch.ResponseResult();
		t2.success = false;
		t2.errors.add('test error');
		HttpResponse getfile = new HttpResponse();
		getfile.setBody(JSON.serialize(t2));
		OP_IntegrationBatch.testresponse.put('getfile', getfile);

		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Ignition Downtime Export Download';
		//mybatch.continueToNextJob = false;
		database.executebatch(mybatch, 1);

		Test.stopTest();


		Integration_Log__c test1 = [Select Id, Status__c from Integration_Log__c where Type__c = 'Ignition Downtime Export' and FTP_File_Name__c = 'Ignition_Downtime_Export_Example.csv'];
		System.assert(test1 != null);

		System.assertEquals('Error', test1.Status__c);

	}

	@isTest
	private static void IgnitionDowntimeExportDownloadDeleteFTPFilesTest() {

		Integration_Log__c il1 = new Integration_Log__c();
		il1.Type__c = 'Ignition Downtime Export';
		il1.Status__c = 'Download Complete';
		il1.FTP_File_Path__c = '/toSF/';
		il1.FTP_File_Name__c = '1.csv';

		insert il1;

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();
		OP_IntegrationBatch.testresponse = new Map<String, HttpResponse> ();

		OP_IntegrationBatch.ResponseResult t2 = new OP_IntegrationBatch.ResponseResult();
		t2.success = true;
		HttpResponse deletefile = new HttpResponse();
		deletefile.setBody(JSON.serialize(t2));
		OP_IntegrationBatch.testresponse.put('deletefile', deletefile);

		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Ignition Downtime Export Download Delete FTP Files';
		//mybatch.continueToNextJob = false;
		database.executebatch(mybatch, 1);

		Test.stopTest();

		Integration_Log__c test1 = [Select Id, Status__c from Integration_Log__c where Id = :il1.Id];
		System.assertEquals('Ready to Process', test1.Status__c);
	}

	@isTest
	private static void IgnitionDowntimeExportDownloadDeleteFTPFilesErrorTest() {

		Integration_Log__c il1 = new Integration_Log__c();
		il1.Type__c = 'Ignition Downtime Export';
		il1.Status__c = 'Download Complete';
		il1.FTP_File_Path__c = '/toSF/';
		il1.FTP_File_Name__c = '1.csv';

		insert il1;

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();
		OP_IntegrationBatch.testresponse = new Map<String, HttpResponse> ();

		OP_IntegrationBatch.ResponseResult t2 = new OP_IntegrationBatch.ResponseResult();
		t2.success = false;
		t2.errors.add('test error');
		HttpResponse deletefile = new HttpResponse();
		deletefile.setBody(JSON.serialize(t2));
		OP_IntegrationBatch.testresponse.put('deletefile', deletefile);

		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Ignition Downtime Export Download Delete FTP Files';
		//mybatch.continueToNextJob = false;
		database.executebatch(mybatch, 1);

		Test.stopTest();

		Integration_Log__c test1 = [Select Id, Status__c from Integration_Log__c where Id = :il1.Id];
		System.assertEquals('Error', test1.Status__c);
	}

	@isTest
	private static void ProcessIgnitionDowntimeExportTest() {

		Account acc1 = new Account();
		acc1.Name = 'Test Account';
		insert acc1;

		//Contact c1 = new Contact;
		//c1.FirstName = 'test';
		//c1.LastName = 'test';
		//insert c1;


		Asset a1 = new Asset();
		a1.Name = 'test asset';
		a1.Asset_Type__c = 'CGP';
		a1.Asset_Search_Type__c = 'CGP';
		a1.Equip_ID__c = '99999';
		a1.AccountId = acc1.Id;
		insert a1;


		Integration_Log__c il1 = new Integration_Log__c();
		il1.Type__c = 'Ignition Downtime Export';
		il1.Status__c = 'Ready to Process';
		il1.FTP_File_Path__c = '/toSF/';
		il1.FTP_File_Name__c = '1.csv';
		insert il1;

		Attachment att1 = new Attachment();
		att1.Name = '1.csv';
		att1.ParentId = il1.Id;
		att1.Body = EncodingUtil.base64Decode('aWQscmVwb3J0RGF0ZSxlcXVpcF9uYW1lLGVxdWlwX2lkLG1ldGVyaWQsZmxvd1R5cGUsZXZlbnRzLGxvbmdlc3Rfb2NjdXIsbG9uZ2VzdF90cyxkdXJhdGlvbgozMDc4LDIwMjAtMDItMDYsUkFORVkgMDEgMDFIIEdBUywyNTI2NSw2MS03MDEsRmxvd2luZywxLDI0LDIwMjAtMDItMDYsMjQuMAozMDc5LDIwMjAtMDItMDYsRUxJWk9ORE8gMDEgMDNIIEdBUyw3NTIyMCw3MS0zNzAzLEZsb3dpbmcsMSwyMy41NTQ4LDIwMjAtMDItMDYsMjMuNTU0NzcwNTU1NTU1NTU3');
		insert att1;

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();

		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Process Ignition Downtime Export';
		//mybatch.continueToNextJob = false;
		database.executebatch(mybatch, 1);

		Test.stopTest();

		Integration_Log__c test1 = [Select Id, Status__c from Integration_Log__c where Id = :il1.Id];
		System.assertEquals('Process Completed', test1.Status__c);
	}

	@isTest
	private static void PrepareDowntimeLogsforProCountTest() {

		Account acc1 = new Account();
		acc1.Name = 'Test Account';
		insert acc1;

		Asset a1 = new Asset();
		a1.Name = 'test asset';
		a1.Asset_Type__c = 'CGP';
		a1.Asset_Search_Type__c = 'CGP';
		a1.Equip_ID__c = '99998';
		a1.AccountId = acc1.Id;
		insert a1;

		Downtime_Log__c dtlog = new Downtime_Log__c();
		dtlog.integration_id__c = '1234';
		dtlog.Date__c = Date.today();
		dtlog.integration_equip_name__c = '1234';
		dtlog.integration_equip_id__c = '1234';
		dtlog.integration_meterId__c = '1234';
		dtlog.intergration_flowType__c = '1234';
		dtlog.integration_events__c = '1234';
		dtlog.longest_occur__c = 24;
		dtlog.integration_longest_ts__c = Date.today();
		dtlog.Duration_hrs__c = 24;
		dtlog.Downtime_Type__c = Downtime_TypeMap.get('Compressor Downtime');
		dtlog.Parent_Code__c = Parent_CodeMap.get('Un-Planned');
		dtlog.Downtime_Code__c = Downtime_CodeMap.get('Cat. Conv. Temp. High');
		dtlog.Asset__c = a1.Id;
		dtlog.Send_To_ProCount__c = true;

		insert dtlog;


		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();

		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Prepare Downtime Logs for ProCount';
		database.executebatch(mybatch, 2000);

		Test.stopTest();

		Integration_Log__c test1 = [Select Id, Status__c from Integration_Log__c where Type__c = 'ProCount Export' AND Status__c = 'Ready to Process'];
		System.assert(test1 != null);
	}

	@isTest
	private static void ProcessDowntimeLogsforProCountTest() {

		Account acc1 = new Account();
		acc1.Name = 'Test Account';
		insert acc1;

		Asset a1 = new Asset();
		a1.Name = 'test asset';
		a1.Asset_Type__c = 'CGP';
		a1.Asset_Search_Type__c = 'CGP';
		a1.Equip_ID__c = '99999';
		a1.AccountId = acc1.Id;
		insert a1;

		Downtime_Log__c dtlog = new Downtime_Log__c();
		dtlog.integration_id__c = '1234';
		dtlog.Date__c = Date.today();
		dtlog.integration_equip_name__c = '1234';
		dtlog.integration_equip_id__c = '1234';
		dtlog.integration_meterId__c = '1234';
		dtlog.intergration_flowType__c = '1234';
		dtlog.integration_events__c = '1234';
		dtlog.longest_occur__c = 24;
		dtlog.integration_longest_ts__c = Date.today();
		dtlog.Duration_hrs__c = 24;
		dtlog.Downtime_Type__c = Downtime_TypeMap.get('Compressor Downtime');
		dtlog.Parent_Code__c = Parent_CodeMap.get('Un-Planned');
		dtlog.Downtime_Code__c = Downtime_CodeMap.get('Cat. Conv. Temp. High');
		dtlog.Asset__c = a1.Id;
		dtlog.Send_To_ProCount__c = true;
		insert dtlog;


		Integration_Log__c il1 = new Integration_Log__c();
		il1.Type__c = 'ProCount Export';
		il1.Status__c = 'Ready to Process';
		il1.FTP_File_Path__c = '/toSF/';
		//il1.FTP_File_Name__c = '1.csv';
		insert il1;


		Map<String, Integer> headers = new Map<String, Integer> ();
		headers.put('id', 0);
		headers.put('reportDate', 1);
		headers.put('equip_name', 2);
		headers.put('equip_id', 3);
		headers.put('meterid', 4);
		headers.put('flowType', 5);
		headers.put('events', 6);
		headers.put('longest_occur', 7);
		headers.put('longest_ts', 8);
		headers.put('duration', 9);
		headers.put('Downtime_Type__c', 10);
		headers.put('Parent_Code__c', 11);
		headers.put('Downtime_Code__c', 12);
		headers.put('SF_Id', 13);

		list<list<String>> downtimedata = new list<list<String>> ();

		list<String> dtlogdata = new list<String> ();
		dtlogdata.add(dtlog.integration_id__c);
		dtlogdata.add(String.valueOf(dtlog.Date__c));
		dtlogdata.add(dtlog.integration_equip_name__c);
		dtlogdata.add(dtlog.integration_equip_id__c);

		dtlogdata.add(dtlog.integration_meterId__c);
		dtlogdata.add(dtlog.intergration_flowType__c);
		dtlogdata.add(dtlog.integration_events__c);
		dtlogdata.add(String.valueOf(dtlog.longest_occur__c));
		dtlogdata.add(String.valueOf(dtlog.integration_longest_ts__c));
		dtlogdata.add(String.valueOf(dtlog.Duration_hrs__c));
		dtlogdata.add(dtlog.Downtime_Type__c);
		dtlogdata.add(dtlog.Parent_Code__c);
		dtlogdata.add(dtlog.Downtime_Code__c);
		dtlogdata.add(dtlog.Id);


		downtimedata.add(dtlogdata);

		OP_IntegrationBatch ob1 = new OP_IntegrationBatch();

		String csvdata = ob1.createcsvdata(headers, downtimedata, true, true);

		Attachment att1 = new Attachment();
		att1.Name = '1.csv';
		att1.ParentId = il1.Id;
		att1.Body = Blob.valueOf(csvdata);
		insert att1;


		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();

		OP_IntegrationBatch.testresponse = new Map<String, HttpResponse> ();
		OP_IntegrationBatch.ResponseResult t1 = new OP_IntegrationBatch.ResponseResult();
		t1.success = true;
		t1.files = new List<String> ();
		//t1.files.add(OP_Utility.OPSettings.ProCount_File_Name__c);
		HttpResponse listfiles = new HttpResponse();
		listfiles.setBody(JSON.serialize(t1));
		OP_IntegrationBatch.testresponse.put('listfiles', listfiles);

		OP_IntegrationBatch.ResponseResult t2 = new OP_IntegrationBatch.ResponseResult();
		t2.success = true;
		HttpResponse addfile = new HttpResponse();
		addfile.setBody(JSON.serialize(t2));
		OP_IntegrationBatch.testresponse.put('addfile', addfile);


		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Process Downtime Logs for ProCount';
		database.executebatch(mybatch, 1);

		Test.stopTest();

		Integration_Log__c test1 = [Select Id, Status__c from Integration_Log__c where Id = :il1.Id];
		System.assertEquals('Process Completed', test1.Status__c);
	}


	@isTest
	private static void ProcessDowntimeLogsforProCountHoldTest() {

		Account acc1 = new Account();
		acc1.Name = 'Test Account';
		insert acc1;

		Asset a1 = new Asset();
		a1.Name = 'test asset';
		a1.Asset_Type__c = 'CGP';
		a1.Asset_Search_Type__c = 'CGP';
		a1.Equip_ID__c = '99999';
		a1.AccountId = acc1.Id;
		insert a1;

		Downtime_Log__c dtlog = new Downtime_Log__c();
		dtlog.integration_id__c = '1234';
		dtlog.Date__c = Date.today();
		dtlog.integration_equip_name__c = '1234';
		dtlog.integration_equip_id__c = '1234';
		dtlog.integration_meterId__c = '1234';
		dtlog.intergration_flowType__c = '1234';
		dtlog.integration_events__c = '1234';
		dtlog.longest_occur__c = 24;
		dtlog.integration_longest_ts__c = Date.today();
		dtlog.Duration_hrs__c = 24;
		dtlog.Downtime_Type__c = Downtime_TypeMap.get('Compressor Downtime');
		dtlog.Parent_Code__c = Parent_CodeMap.get('Un-Planned');
		dtlog.Downtime_Code__c = Downtime_CodeMap.get('Cat. Conv. Temp. High');
		dtlog.Asset__c = a1.Id;
		dtlog.Send_To_ProCount__c = true;
		insert dtlog;


		Integration_Log__c il1 = new Integration_Log__c();
		il1.Type__c = 'ProCount Export';
		il1.Status__c = 'Ready to Process';
		il1.FTP_File_Path__c = '/toSF/';
		//il1.FTP_File_Name__c = '1.csv';
		insert il1;


		Map<String, Integer> headers = new Map<String, Integer> ();
		headers.put('id', 0);
		headers.put('reportDate', 1);
		headers.put('equip_name', 2);
		headers.put('equip_id', 3);
		headers.put('meterid', 4);
		headers.put('flowType', 5);
		headers.put('events', 6);
		headers.put('longest_occur', 7);
		headers.put('longest_ts', 8);
		headers.put('duration', 9);
		headers.put('Downtime_Type__c', 10);
		headers.put('Parent_Code__c', 11);
		headers.put('Downtime_Code__c', 12);
		headers.put('SF_Id', 13);

		list<list<String>> downtimedata = new list<list<String>> ();

		list<String> dtlogdata = new list<String> ();
		dtlogdata.add(dtlog.integration_id__c);
		dtlogdata.add(String.valueOf(dtlog.Date__c));
		dtlogdata.add(dtlog.integration_equip_name__c);
		dtlogdata.add(dtlog.integration_equip_id__c);

		dtlogdata.add(dtlog.integration_meterId__c);
		dtlogdata.add(dtlog.intergration_flowType__c);
		dtlogdata.add(dtlog.integration_events__c);
		dtlogdata.add(String.valueOf(dtlog.longest_occur__c));
		dtlogdata.add(String.valueOf(dtlog.integration_longest_ts__c));
		dtlogdata.add(String.valueOf(dtlog.Duration_hrs__c));
		dtlogdata.add(dtlog.Downtime_Type__c);
		dtlogdata.add(dtlog.Parent_Code__c);
		dtlogdata.add(dtlog.Downtime_Code__c);
		dtlogdata.add(dtlog.Id);


		downtimedata.add(dtlogdata);

		OP_IntegrationBatch ob1 = new OP_IntegrationBatch();

		String csvdata = ob1.createcsvdata(headers, downtimedata, true, true);

		Attachment att1 = new Attachment();
		att1.Name = '1.csv';
		att1.ParentId = il1.Id;
		att1.Body = Blob.valueOf(csvdata);
		insert att1;


		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();

		OP_IntegrationBatch.testresponse = new Map<String, HttpResponse> ();
		OP_IntegrationBatch.ResponseResult t1 = new OP_IntegrationBatch.ResponseResult();
		t1.success = true;
		t1.files = new List<String> ();
		t1.files.add(settings.ProCount_File_Name__c);
		HttpResponse listfiles = new HttpResponse();
		listfiles.setBody(JSON.serialize(t1));
		OP_IntegrationBatch.testresponse.put('listfiles', listfiles);

		OP_IntegrationBatch.ResponseResult t2 = new OP_IntegrationBatch.ResponseResult();
		t2.success = true;
		HttpResponse addfile = new HttpResponse();
		addfile.setBody(JSON.serialize(t2));
		OP_IntegrationBatch.testresponse.put('addfile', addfile);


		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Process Downtime Logs for ProCount';
		database.executebatch(mybatch, 1);

		Test.stopTest();

		Integration_Log__c test1 = [Select Id, Status__c from Integration_Log__c where Id = :il1.Id];
		System.assertEquals('Holding', test1.Status__c);
	}


	@isTest
	private static void CleanupIntegrationLogsTest() {

		Integration_Log__c il1 = new Integration_Log__c();
		il1.Type__c = 'ProCount Export';
		il1.Status__c = 'Ready to Process';
		il1.FTP_File_Path__c = '/toSF/';
		il1.CreatedDate = Datetime.now().addDays(- 400);
		insert il1;

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();

		System.assertEquals(365, OP_IntegrationBatch.IntegrationLogCleanupDays);


		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Cleanup Integration Logs';
		mybatch.query = 'Select Id From Integration_Log__c Where IsDeleted = false and Id = \'' + il1.Id + '\'';
		database.executebatch(mybatch, 200);

		Test.stopTest();

		Integration_Log__c test1 = [Select Id, Status__c, IsDeleted from Integration_Log__c where Id = :il1.Id ALL ROWS];
		System.assertEquals(true, test1.IsDeleted);
	}


	@isTest
	private static void CleanupDowntimeLogsTest() {

		Account acc1 = new Account();
		acc1.Name = 'Test Account';
		insert acc1;

		Asset a1 = new Asset();
		a1.Name = 'test asset';
		a1.Asset_Type__c = 'CGP';
		a1.Asset_Search_Type__c = 'CGP';
		a1.Equip_ID__c = '99999';
		a1.AccountId = acc1.Id;
		insert a1;

		Downtime_Log__c dtlog = new Downtime_Log__c();
		dtlog.integration_id__c = '1234';
		dtlog.Date__c = Date.today();
		dtlog.integration_equip_name__c = '1234';
		dtlog.integration_equip_id__c = '1234';
		dtlog.integration_meterId__c = '1234';
		dtlog.intergration_flowType__c = '1234';
		dtlog.integration_events__c = '1234';
		dtlog.longest_occur__c = 24;
		dtlog.integration_longest_ts__c = Date.today();
		dtlog.Duration_hrs__c = 24;
		dtlog.Downtime_Type__c = Downtime_TypeMap.get('Compressor Downtime');
		dtlog.Parent_Code__c = Parent_CodeMap.get('Un-Planned');
		dtlog.Downtime_Code__c = Downtime_CodeMap.get('Cat. Conv. Temp. High');
		dtlog.Asset__c = a1.Id;
		dtlog.Send_To_ProCount__c = true;
		insert dtlog;

		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();

		System.assertEquals(365, OP_IntegrationBatch.DowntimeLogCleanupDays);

		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Cleanup Downtime Logs';
		mybatch.query = 'Select Id From Downtime_Log__c Where IsDeleted = false and Id = \'' + dtlog.Id + '\'';
		database.executebatch(mybatch, 200);

		Test.stopTest();

		Downtime_Log__c test1 = [Select Id, IsDeleted from Downtime_Log__c where Id = :dtlog.Id ALL ROWS];
		System.assertEquals(true, test1.IsDeleted);
	}

	@isTest
	private static void scheduleTest() {


		Test.startTest();
		OP_Utility.OPSettings.Enable_Logging__c = true;
		Ignition_ProCount_Integration_Settings__mdt settings = getTestSettings();



		System.schedule('Daily OPTEST_IntegrationBatch Job', '0 0 2 * * ?', new OP_IntegrationBatch());

		Test.stopTest();


	}



}