unpackaged/main/default/objects/Asset/fields/Equip_ID__c.field-meta.xml
<CustomField>
    <fullName>Equip_ID__c</fullName>
    <label>Equip ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/Downtime_Log__c.object-meta.xml
<CustomObject>
    <label>Downtime Log</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>Downtime Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Downtime Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Downtime_Log__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Asset_Type__c</field>
            <operation>equals</operation>
            <value>Engine/Compressor, Well</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Downtime Logs</relationshipLabel>
    <relationshipName>Downtime_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Downtime_Code__c.field-meta.xml
<CustomField>
    <fullName>Downtime_Code__c</fullName>
    <label>Downtime Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Parent_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>54</fullName>
                <label>Cat. Conv. Temp. High</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Chemical Treatment</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>Compressor Issue</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Compressor Issues</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Compressor PM</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>Cooling Water Level Low</label>
            </value>
            <value>
                <fullName>47</fullName>
                <label>Cooling Water Temperature High</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>Down-hole Issue/ No Flow</label>
            </value>
            <value>
                <fullName>44</fullName>
                <label>Facility Maintenance</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Facility  Maintenance</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Flowline Maintenance</label>
            </value>
            <value>
                <fullName>58</fullName>
                <label>Force Majeure</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Freezing Issue/ Hydrates</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Fueld Gas Supply</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Gas Lift</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Gas  Lift</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Gas Plant Shut-in</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>Gas Temperature High</label>
            </value>
            <value>
                <fullName>57</fullName>
                <label>High Discharge Pressure</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>High Pipeline Pressure</label>
            </value>
            <value>
                <fullName>59</fullName>
                <label>High Sales Line Pressure</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Hot Water Operations</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Hot-Water Operations</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>I&amp;E Issue</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Loaded Up/ Incapable of flow</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>Lube No Flow</label>
            </value>
            <value>
                <fullName>49</fullName>
                <label>Lube Oil Level High</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>Lube Oil Pressure High</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>Lube Oil Temperature High</label>
            </value>
            <value>
                <fullName>Not In Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Downtime_Type__c.field-meta.xml
<CustomField>
    <fullName>Downtime_Type__c</fullName>
    <label>Downtime Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compressor Downtime</fullName>
            </value>
            <value>
                <fullName>Well Downtime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Duration_hrs__c.field-meta.xml
<CustomField>
    <fullName>Duration_hrs__c</fullName>
    <label>Duration (hrs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_equip_id__c.field-meta.xml
<CustomField>
    <fullName>integration_equip_id__c</fullName>
    <inlineHelpText>Value from integration file</inlineHelpText>
    <label>integration_equip_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_equip_name__c.field-meta.xml
<CustomField>
    <fullName>integration_equip_name__c</fullName>
    <inlineHelpText>Value fro integration file</inlineHelpText>
    <label>integration_equip_name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_events__c.field-meta.xml
<CustomField>
    <fullName>integration_events__c</fullName>
    <label>integration_events</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_id__c.field-meta.xml
<CustomField>
    <fullName>integration_id__c</fullName>
    <label>integration id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_longest_ts__c.field-meta.xml
<CustomField>
    <fullName>integration_longest_ts__c</fullName>
    <label>integration longest_ts</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_meterId__c.field-meta.xml
<CustomField>
    <fullName>integration_meterId__c</fullName>
    <label>integration meterId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/intergration_flowType__c.field-meta.xml
<CustomField>
    <fullName>intergration_flowType__c</fullName>
    <label>intergration flowType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/longest_occur__c.field-meta.xml
<CustomField>
    <fullName>longest_occur__c</fullName>
    <label>longest_occur</label>
    <precision>17</precision>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Parent_Code__c.field-meta.xml
<CustomField>
    <fullName>Parent_Code__c</fullName>
    <label>Parent Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Downtime_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>42</fullName>
                <label>Planned</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Planned/Subsurface</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planned/Surface</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Un-Planned</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Un-Planned/Subsurface</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Un-Planned/Surface</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/ProCount_Last_Update__c.field-meta.xml
<CustomField>
    <fullName>ProCount_Last_Update__c</fullName>
    <inlineHelpText>The date the downtime log was set to ProCount to be processed</inlineHelpText>
    <label>ProCount Last Update</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Send_To_ProCount__c.field-meta.xml
<CustomField>
    <fullName>Send_To_ProCount__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to send to ProCount</inlineHelpText>
    <label>Send To ProCount</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <description>Used to track and process integration data</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{0}</displayFormat>
        <label>Integration Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Integration_Log__c/fields/FTP_File_Name__c.field-meta.xml
<CustomField>
    <fullName>FTP_File_Name__c</fullName>
    <label>FTP File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/FTP_File_Path__c.field-meta.xml
<CustomField>
    <fullName>FTP_File_Path__c</fullName>
    <label>FTP File Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <description>included process information</description>
    <label>Log</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Download Complete</fullName>
            </value>
            <value>
                <fullName>Process Completed</fullName>
            </value>
            <value>
                <fullName>Upload Complete</fullName>
            </value>
            <value>
                <fullName>Ready to Process</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Holding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Integration_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ignition Downtime Export</fullName>
            </value>
            <value>
                <fullName>ProCount Export</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OP_IntegrationStatusController.cls
/**
 * @author Bruce Behrens Opportune LLP
 * @description controller for LWC OpIntegrationStatus
 * @date 1-30-2020
*/
public with sharing class OP_IntegrationStatusController {

	@AuraEnabled
	public static String addNewSchedule(string name, Integer hour, Integer minute)
	{
		try{
			System.schedule('Daily OP_IntegrationBatch Job: ' + name, '0 ' + minute + ' ' + hour + ' * * ?', new OP_IntegrationBatch());
		} 
		catch(Exception ex){
			return 'Error: ' + ex.getMessage();
		}
		return '';
	}

	@AuraEnabled
	public static list<Sobject> getScheduledJobs()
	{
		return[SELECT ID, CronExpression, CronJobDetail.JobType, CronJobDetail.Name, CronJobDetailId, EndTime, NextFireTime, PreviousFireTime, StartTime, State, TimesTriggered FROM CronTrigger where CronJobDetail.Name like '%OP_IntegrationBatch%' order by NextFireTime desc];
	}

	@AuraEnabled
	public static list<Sobject> getApexJobs()
	{
		return[SELECT Id, CreatedDate, CreatedById, JobType, ApexClass.Name, ApexClassId, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors, CompletedDate, MethodName, ExtendedStatus, ParentJobId, LastProcessed, LastProcessedOffset FROM AsyncApexJob where ApexClass.Name like '%OP_IntegrationBatch%' order by CompletedDate desc limit 100];
	}

	@AuraEnabled
	public static list<Sobject> getIntegrationLogs()
	{
		return[SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastViewedDate, LastReferencedDate, Type__c, Status__c, Log__c, FTP_File_Path__c, FTP_File_Name__c FROM Integration_Log__c order by CreatedDate desc limit 100];
	}

	@AuraEnabled
	public static void runJobNow()
	{
		OP_IntegrationBatch mybatch = new OP_IntegrationBatch();
		mybatch.JobType = 'Ignition Downtime Export Download';
		database.executebatch(mybatch, 1);
	}

	@AuraEnabled
	public static list<Sobject> getReadyForProCount()
	{
		return[SELECT Id, Name, CreatedDate, LastModifiedDate, Asset__r.Name, Asset__r.Equip_ID__c, Asset__c, Duration_hrs__c, Date__c, Downtime_Type__c, Parent_Code__c, Downtime_Code__c, integration_equip_id__c, integration_equip_name__c, longest_occur__c, integration_id__c, integration_meterId__c, intergration_flowType__c, integration_events__c, integration_longest_ts__c, Send_To_ProCount__c, ProCount_Last_Update__c FROM Downtime_Log__c where Send_To_ProCount__c = true order by LastModifiedDate desc limit 1000];
	}

	@AuraEnabled
	public static list<Sobject> getRecentDowntimeLogs()
	{
		return[SELECT Id, Name, CreatedDate, LastModifiedDate, Asset__r.Name, Asset__r.Equip_ID__c, Asset__c, Duration_hrs__c, Date__c, Downtime_Type__c, Parent_Code__c, Downtime_Code__c, integration_equip_id__c, integration_equip_name__c, longest_occur__c, integration_id__c, integration_meterId__c, intergration_flowType__c, integration_events__c, integration_longest_ts__c, Send_To_ProCount__c, ProCount_Last_Update__c FROM Downtime_Log__c order by LastModifiedDate desc limit 250];
	}

}