unpackaged/main/default/objects/Asset/fields/Equip_ID__c.field-meta.xml
<CustomField>
    <fullName>Equip_ID__c</fullName>
    <label>Equip ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/Downtime_Log__c.object-meta.xml
<CustomObject>
    <label>Downtime Log</label>
    <nameField>
        <displayFormat>DL-{0}</displayFormat>
        <label>Downtime Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Downtime Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Downtime_Log__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <label>Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Asset_Type__c</field>
            <operation>equals</operation>
            <value>Engine/Compressor, Well</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Downtime Logs</relationshipLabel>
    <relationshipName>Downtime_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Downtime_Code__c.field-meta.xml
<CustomField>
    <fullName>Downtime_Code__c</fullName>
    <label>Downtime Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Parent_Code__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>54</fullName>
                <label>Cat. Conv. Temp. High</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>Chemical Treatment</label>
            </value>
            <value>
                <fullName>41</fullName>
                <label>Compressor Issue</label>
            </value>
            <value>
                <fullName>35</fullName>
                <label>Compressor Issues</label>
            </value>
            <value>
                <fullName>30</fullName>
                <label>Compressor PM</label>
            </value>
            <value>
                <fullName>50</fullName>
                <label>Cooling Water Level Low</label>
            </value>
            <value>
                <fullName>47</fullName>
                <label>Cooling Water Temperature High</label>
            </value>
            <value>
                <fullName>64</fullName>
                <label>Down-hole Issue/ No Flow</label>
            </value>
            <value>
                <fullName>44</fullName>
                <label>Facility Maintenance</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>Facility  Maintenance</label>
            </value>
            <value>
                <fullName>24</fullName>
                <label>Flowline Maintenance</label>
            </value>
            <value>
                <fullName>58</fullName>
                <label>Force Majeure</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>Freezing Issue/ Hydrates</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>Fueld Gas Supply</label>
            </value>
            <value>
                <fullName>37</fullName>
                <label>Gas Lift</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>Gas  Lift</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Gas Plant Shut-in</label>
            </value>
            <value>
                <fullName>52</fullName>
                <label>Gas Temperature High</label>
            </value>
            <value>
                <fullName>57</fullName>
                <label>High Discharge Pressure</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>High Pipeline Pressure</label>
            </value>
            <value>
                <fullName>59</fullName>
                <label>High Sales Line Pressure</label>
            </value>
            <value>
                <fullName>32</fullName>
                <label>Hot Water Operations</label>
            </value>
            <value>
                <fullName>31</fullName>
                <label>Hot-Water Operations</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>I&amp;E Issue</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>Loaded Up/ Incapable of flow</label>
            </value>
            <value>
                <fullName>45</fullName>
                <label>Lube No Flow</label>
            </value>
            <value>
                <fullName>49</fullName>
                <label>Lube Oil Level High</label>
            </value>
            <value>
                <fullName>46</fullName>
                <label>Lube Oil Pressure High</label>
            </value>
            <value>
                <fullName>53</fullName>
                <label>Lube Oil Temperature High</label>
            </value>
            <value>
                <fullName>Not In Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Downtime_Type__c.field-meta.xml
<CustomField>
    <fullName>Downtime_Type__c</fullName>
    <label>Downtime Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compressor Downtime</fullName>
            </value>
            <value>
                <fullName>Well Downtime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Duration_hrs__c.field-meta.xml
<CustomField>
    <fullName>Duration_hrs__c</fullName>
    <label>Duration (hrs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_equip_id__c.field-meta.xml
<CustomField>
    <fullName>integration_equip_id__c</fullName>
    <inlineHelpText>Value from integration file</inlineHelpText>
    <label>integration_equip_id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_equip_name__c.field-meta.xml
<CustomField>
    <fullName>integration_equip_name__c</fullName>
    <inlineHelpText>Value fro integration file</inlineHelpText>
    <label>integration_equip_name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_events__c.field-meta.xml
<CustomField>
    <fullName>integration_events__c</fullName>
    <label>integration_events</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_id__c.field-meta.xml
<CustomField>
    <fullName>integration_id__c</fullName>
    <label>integration id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_longest_ts__c.field-meta.xml
<CustomField>
    <fullName>integration_longest_ts__c</fullName>
    <label>integration longest_ts</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/integration_meterId__c.field-meta.xml
<CustomField>
    <fullName>integration_meterId__c</fullName>
    <label>integration meterId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/intergration_flowType__c.field-meta.xml
<CustomField>
    <fullName>intergration_flowType__c</fullName>
    <label>intergration flowType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/longest_occur__c.field-meta.xml
<CustomField>
    <fullName>longest_occur__c</fullName>
    <label>longest_occur</label>
    <precision>17</precision>
    <scale>15</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Parent_Code__c.field-meta.xml
<CustomField>
    <fullName>Parent_Code__c</fullName>
    <label>Parent Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Downtime_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>42</fullName>
                <label>Planned</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Planned/Subsurface</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Planned/Surface</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>Un-Planned</label>
            </value>
            <value>
                <fullName>40</fullName>
                <label>Un-Planned/Subsurface</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Un-Planned/Surface</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/ProCount_Last_Update__c.field-meta.xml
<CustomField>
    <fullName>ProCount_Last_Update__c</fullName>
    <inlineHelpText>The date the downtime log was set to ProCount to be processed</inlineHelpText>
    <label>ProCount Last Update</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Downtime_Log__c/fields/Send_To_ProCount__c.field-meta.xml
<CustomField>
    <fullName>Send_To_ProCount__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to send to ProCount</inlineHelpText>
    <label>Send To ProCount</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/dowtimeLogsManagerController.cls
/**
 * @author Bruce Behrens Opportune LLP
 * @description controller for LWC dowtimeLogsManager
 * @date 2-4-2020
*/
public with sharing class dowtimeLogsManagerController {

	@AuraEnabled
	public static list<Sobject> getDowntimeLogs(map<string, string> searchfor)
	{
		OP_Utility.log('***getDowntimeLogs searchfor: ' + searchfor);


		String myquery = ' SELECT Id, Name, CreatedDate, LastModifiedDate, Asset__r.Name, Asset__r.Equip_ID__c, Asset__c, Duration_hrs__c, Date__c, Downtime_Type__c, Parent_Code__c, Downtime_Code__c, integration_equip_id__c, integration_equip_name__c, longest_occur__c, integration_id__c, integration_meterId__c, intergration_flowType__c, integration_events__c, integration_longest_ts__c, Send_To_ProCount__c, ProCount_Last_Update__c FROM Downtime_Log__c Where IsDeleted = false ';

		if (searchfor != null)
		{
			string myqueryAdditionalWhere = String.join(new list<String> (OP_Utility.buildWhere(new Map<string, string> { 'Asset__c' => 'REFERENCE', 'Downtime_Type__c' => 'PICKLIST', 'Parent_Code__c' => 'PICKLIST', 'Downtime_Code__c' => 'PICKLIST', 'Date__c' => 'DATE' }, searchfor).values()), ' AND ');
			if (String.isNotBlank(myqueryAdditionalWhere))
			{
				myquery += ' AND ' + myqueryAdditionalWhere;
			}
		}

		myquery += ' Limit 1000';
		OP_Utility.log('***getRecords myquery: ' + myquery);

		return Database.query(myquery);
	}


	@AuraEnabled
	public static String copyLogs(List<Id> sourceIds, Date newDate)
	{
		OP_Utility.log('***copyLogs newDate: ' + newDate + ' sourceIds: ' + sourceIds);
		
		List<Downtime_Log__c> newLogs = new List<Downtime_Log__c> ();
		List<Downtime_Log__c> logs = new List<Downtime_Log__c> ([SELECT Id, Name, Asset__c, Duration_hrs__c, Date__c, Downtime_Type__c, Parent_Code__c, Downtime_Code__c, integration_equip_id__c, integration_equip_name__c, longest_occur__c, integration_id__c, integration_meterId__c, intergration_flowType__c, integration_events__c, integration_longest_ts__c, Send_To_ProCount__c, ProCount_Last_Update__c FROM Downtime_Log__c Where IsDeleted = false and Id in :sourceIds]);
		
		//Date dt1 = Date.valueOf(newDate);
		
		//Datetime dt1 = Datetime.newInstanceGmt(newDate, Time.newInstance(12,0,0,0));
		//OP_Utility.log('***copyLogs dt1: ' + dt1);
		//OP_Utility.log('***copyLogs dt1.date: ' + dt1.date());
		//OP_Utility.log('***copyLogs dt1.dateGmt: ' + dt1.dateGmt());
		for (Downtime_Log__c item :logs) {

			Downtime_Log__c dtnew = item.clone(false, false, false, false);
			dtnew.Date__c = newDate;//Date.newInstance(dt1.year(),dt1.month(), dt1.day());
			//dtnew.Send_To_ProCount__c = true;
			newLogs.add(dtnew);

			OP_Utility.log('***copyLogs dtnew.Date__c: ' + dtnew.Date__c);
		}
		List<Database.SaveResult> saveresults = Database.insert(newLogs, false);
		List<String> errors = new List<String>();
		List<String> sourceerrornames = new List<String>();


		List<Downtime_Log__c> updateLogs = new List<Downtime_Log__c> ();
		for(Integer i = 0; i < saveresults.size(); i++){
			Downtime_Log__c source = logs[i];
			Database.SaveResult sr = saveresults[i];
			if (sr.isSuccess() == false)
			{
				sourceerrornames.add(source.Name);
				for(Database.Error de : sr.getErrors()){
					errors.add(de.getMessage());
				}
			}
			else{
				updateLogs.add(source);
			}
		}
		//calling update so we can fire process builder that check Send_To_ProCount__c based on configured criteria. 
		if (updateLogs.isEmpty() == false){
			update logs;
		}

		return sourceerrornames.isEmpty() ? '' : 'Not able to copy logs ('+ String.join(sourceerrornames, ',') +') details: ' + String.join(errors, ' | ') ;
	}


	@AuraEnabled
	public static String deleteLogs(List<Id> sourceIds)
	{
		OP_Utility.log('***deleteLogs sourceIds: ' + sourceIds);
		List<Downtime_Log__c> logs = new List<Downtime_Log__c> ([SELECT Id FROM Downtime_Log__c Where IsDeleted = false and Id in :sourceIds]);
		if (logs.isEmpty() == false) {
			delete logs;
		}
		return '';
	}

}